local QBCore = exports['qb-core']:GetCoreObject()

AC = {

    [1] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs."
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
                
                [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
                [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
                [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
                [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
                [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
                [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
                [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
                [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
                [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
                [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
                [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
                [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
                [13] = {
                    ["name"] = "Baking Soda",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "bakingsoda.png",
                    ["itemname"] = "bakingsoda",
                },
                [14] = {
                    ["name"] = "Empty Vial",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "lsd_vial_two.png",
                    ["itemname"] = "emptyvial",
                },
                [15] = {
                    ["name"] = "Needle",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "knife.png",
                    ["itemname"] = "needle",
                },
                [16] = {
                    ["name"] = "Camera",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "camera.png",
                    ["itemname"] = "polaroid_camera",
                },
                [17] = {
                    ["name"] = "Polaroid Paper",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "polaroid_paper.png",
                    ["itemname"] = "polaroid_paper",
                },
                [18] = {
                    ["name"] = "Fitbit",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "fitbit.png",
                    ["itemname"] = "fitbit",
                },
                [19] = {
                    ["name"] = "Rubikcube",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "rubikcube.png",
                    ["itemname"] = "rubikcube",
                },
                [20] = {
                    ["name"] = "White Watch",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "watch_white.png",
                    ["itemname"] = "watch_white",
                },
                [21] = {
                    ["name"] = "Black Watch",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "watch_black.png",
                    ["itemname"] = "watch_black",
                },
            },
        }
    },
    [2] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    }, 
    [3] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    }, 
    [4] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    }, 
    [5] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ------["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    }, 
    [6] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    }, 
    [7] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    }, 
    [8] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    },
    [9] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [2] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [3] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [4] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [5] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [6] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [7] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [8] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [9] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [10] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [11] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    },
    [10] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    },
    [11] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    },
    [12] = { 
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        }
    },
    [13] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        },
    },
    [14] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        },
    },
    [15] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [2] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [3] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [4] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [5] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [6] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [7] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [8] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [9] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [10] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [11] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        },
    },
    [16] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        },
    },
    [17] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        },
    },
    [18] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                ["name"] = "Armor",
                ["price"] = 100,
                ["amount"] = 1,
                ["type"] = "weapon",
                ["image"] = "armor.png",
                ["itemname"] = "armor",
            },
            [2] = {
                    ["name"] = "Handcuffs",
                    ["price"] = 130,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "handcuffs.png",
                    ["itemname"] = "handcuffs",
                },
            [3] = {
                    ["name"] = "Painkillers",
                    ["price"] = 170,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "painkillers.png",
                    ["itemname"] = "painkillers",
                },
            [4] = {
                    ["name"] = "Radio",
                    ["price"] = 160,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "radio.png",
                    ["itemname"] = "radio",
                },
            [5] = {
                    ["name"] = "Radioscanner",
                    ["price"] = 110,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "radioscanner.png",
                    ["itemname"] = "radioscanner",
                },
            [6] = {
                    ["name"] = "Repairkit",
                    ["price"] = 155,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "repairkit.png",
                    ["itemname"] = "repairkit",
                },
            [7] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [8] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [9] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [10] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [11] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [12] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [13] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [14] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [15] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [16] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [17] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [18] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        },
    },
    [19] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 100,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 250,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                },
            },
        },
    },
    [20] = {
        ["name"] = "TO OPEN",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                    ["name"] = "Snikkel Candy",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "snikkel_candy.png",
                    ["itemname"] = "snikkel_candy",
                },
            [2] = {
                    ["name"] = "tosti",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "tosti.png",
                    ["itemname"] = "tosti",
                },
            [3] = {
                    ["name"] = "Water",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "water_bottle.png",
                    ["itemname"] = "water_bottle",
                },
            [4] = {
                    ["name"] = "Beer",
                    ["price"] = 9,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "beer.png",
                    ["itemname"] = "beer",
                },
            [5] = {
                    ["name"] = "Cola",
                    ["price"] = 12,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "cola.png",
                    ["itemname"] = "kurkakola",
                },
            [6] = {
                    ["name"] = "Sandwich",
                    ["price"] = 15,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "sandwich.png",
                    ["itemname"] = "sandwich",
                },
            [7] = {
                    ["name"] = "Twerks Candy",
                    ["price"] = 11,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "twerks_candy.png",
                    ["itemname"] = "twerks_candy",
                },
            [8] = {
                    ["name"] = "Ball",
                    ["price"] = 17,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_ball.png",
                    ["itemname"] = "weapon_ball",
                },
            [9] = {
                    ["name"] = "Petrolcan",
                    ["price"] = 18,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_petrolcan.png",
                    ["itemname"] = "weapon_petrolcan",
                },
            [10] = {
                    ["name"] = "Whiskey",
                    ["price"] = 20,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "whiskey.png",
                    ["itemname"] = "whiskey",
                },
            [11] = {
                    ["name"] = "Wine",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "wine.png",
                    ["itemname"] = "wine",
                },
            [12] = {
                    ["name"] = "Sticky Note",
                    ["price"] = 21,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "stickynote.png",
                    ["itemname"] = "stickynote",
                },
            },
            ["Knifes"] = {
                [1] = {
                    ["name"] = "Knife",
                    ["price"] = 2500,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_knife.png",
                    ["itemname"] = "weapon_knife",
                },
                [2] = {
                    ["name"] = "Dagger",
                    ["price"] = 6000,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_dagger.png",
                    ["itemname"] = "weapon_dagger",
                }, 
            },
        },
    },
    [21] = {
        ["name"] = "TOOLSHOP",
        ["category"] = "All In One",
        ["job"] = "",
        ["categoryList"] = {
            ["General"] = "Diverse items for various needs.",
            ["Knifes"] = "Assortment of sharp cutting tools.",
            ---["Weapons"] = "Lethal tools for self-defense.",
        },
        ["itemList"] = {
            ["General"] = { --["General Items"] --This category will be active when the page is first opened. This place should not be empty.
            [1] = {
                ["name"] = "Armor",
                ["price"] = 25000,
                ["amount"] = 1,
                ["type"] = "weapon",
                ["image"] = "armor.png",
                ["itemname"] = "armor",
            },
            [2] = {
                    ["name"] = "Handcuffs",
                    ["price"] = 20000,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "handcuffs.png",
                    ["itemname"] = "handcuffs",
                },
            [3] = {
                    ["name"] = "weapon_crowbar",
                    ["price"] = 2000,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "weapon_crowbar.png",
                    ["itemname"] = "weapon_crowbar",
                },
            [4] = {
                    ["name"] = "Radio",
                    ["price"] = 160,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "radio.png",
                    ["itemname"] = "radio",
                },
            [5] = {
                    ["name"] = "Radioscanner",
                    ["price"] = 110,
                    ["amount"] = 1,
                    ["type"] = "weapon",
                    ["image"] = "radioscanner.png",
                    ["itemname"] = "radioscanner",
                },
            },
        },
    }, 
}


Pos = {
    [1] = vector3(24.47, -1346.62, 30.0),
    [2] = vector3(-3039.54, 584.38, 8.31),
    [3] = vector3(-3242.97, 1000.01, 13.23),
    [4] = vector3(1728.07, 6415.63, 35.04),
    [5] = vector3(1959.82, 3740.48, 32.34),
    [6] = vector3(549.13, 2670.85, 42.16),
    [7] = vector3(2677.47, 3279.76, 55.24),
    [8] = vector3(2556.66, 380.84, 108.62),
    [9] = vector3(372.66, 326.98, 103.57),
    [10] = vector3(-47.02, -1758.23, 29.42),
    [11] = vector3(-706.06, -913.97, 19.22),
    [12] = vector3(-1820.02, 794.03, 138.09),
    [13] = vector3(1164.71, -322.94, 69.21),
    [14] = vector3(1697.87, 4922.96, 42.06),
    [15] = vector3(-1221.58, -908.15, 12.33),
    [16] = vector3(-1486.59, -377.68, 40.16),
    [17] = vector3(-2966.39, 391.42, 15.04),
    [18] = vector3(1165.17, 2710.88, 38.16),
    [19] = vector3(1134.2, -982.91, 46.42),
    [20] = vector3(1134.2, -982.91, 46.42),
    [21] = vector3(46.62, -1749.7, 29.63)
}

function AC.Error(cb)
    TriggerClientEvent('QBCore:Notify', source, "You don't have enough balance.", "error")
end

function AC.Success()
    TriggerClientEvent('QBCore:Notify', source, "The purchase process is successful.", "success")
end
